sonar.projectKey=jonathanspereira_condoflow
sonar.organization=jonathanspereira
sonar.projectName=CondoFlow
sonar.projectVersion=1.0

# Path to the source code
sonar.sources=app,components,lib
sonar.exclusions=**/*.test.tsx,**/*.spec.tsx,node_modules/**,.next/**

# Path to test files
sonar.tests=app
sonar.test.inclusions=**/*.test.tsx,**/*.spec.tsx

# Coverage
sonar.javascript.lcov.reportPaths=coverage/lcov.info
