spring.application.name=condoflow

spring:
datasource:
url: jdbc:postgresql://localhost:5432/condoflow_db
username: condoflow_user
password: condoflow_password
jpa:
hibernate:
ddl-auto: update # Útil em dev para criar as tabelas automaticamente
show-sql: true
properties:
format_sql: true

# Configurações de Conexão com o Banco de Dados (Exatamente iguais ao Docker)spring.datasource.url=jdbc:postgresql://db:5432/condoflow_db
#spring.datasource.username=condoflow_user
#spring.datasource.password=condoflow_password
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
spring.datasource.driver-class-name=org.postgresql.Driver

# Configurações do JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true