spring.application.name=condoflow

spring:
datasource:
url: jdbc:postgresql://localhost:5432/condoflow_db
username: condoflow_user
password: condoflow_password
jpa:
hibernate:
ddl-auto: update # Útil em dev para criar as tabelas automaticamente
show-sql: true
properties:
hibernate:
format_sql: true
