spring.application.name=condoflow

# Configurações de Banco H2 para Testes
spring.datasource.url=jdbc:h2:mem:condoflow_test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=PostgreSQL
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false

# Configurações de E-mail (Mock / Test)
spring.mail.host=localhost
spring.mail.port=25
spring.mail.username=test@condoflow.com
spring.mail.password=test
app.frontend.url=http://localhost:3000
